// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	operationLogFieldNames          = builder.RawFieldNames(&OperationLog{})
	operationLogRows                = strings.Join(operationLogFieldNames, ",")
	operationLogRowsExpectAutoSet   = strings.Join(stringx.Remove(operationLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	operationLogRowsWithPlaceHolder = strings.Join(stringx.Remove(operationLogFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheOperationLogIdPrefix = "cache:operationLog:id:"
)

type (
	operationLogModel interface {
		Where(query string, args ...interface{}) *defaultOperationLogModel
		Limit(limit int) *defaultOperationLogModel
		Offset(offset int) *defaultOperationLogModel
		OrderBy(query string) *defaultOperationLogModel
		First(ctx context.Context) (*OperationLog, error)
		Find(ctx context.Context) ([]*OperationLog, error)
		Count(ctx context.Context) (int64, error)
		Insert(ctx context.Context, data *OperationLog) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*OperationLog, error)
		Update(ctx context.Context, data *OperationLog) error
		Delete(ctx context.Context, id int64) error
	}

	defaultOperationLogModel struct {
		sqlc.CachedConn
		table     string
		query     string
		queryArgs []interface{}
		limit     int
		offset    int
		orderBy   string
	}

	OperationLog struct {
		Id             int64     `db:"id"`
		OperationAt    time.Time `db:"operation_at"`    // 操作时间
		UserId         string    `db:"user_id"`         // 用户id
		Username       string    `db:"username"`        // 用户名
		Operation      string    `db:"operation"`       // 用户操作
		Method         string    `db:"method"`          // 请求方法
		RequestParams  string    `db:"request_params"`  // 请求参数
		ResponseParams string    `db:"response_params"` // 响应参数
		Time           int64     `db:"time"`            // 执行时长(毫秒)
		Ip             string    `db:"ip"`              // IP地址
	}
)

func newOperationLogModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultOperationLogModel {
	return &defaultOperationLogModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`operation_log`",
	}
}

func (m *defaultOperationLogModel) withSession(session sqlx.Session) *defaultOperationLogModel {
	return &defaultOperationLogModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`operation_log`",
	}
}

func (m *defaultOperationLogModel) Where(query string, args ...interface{}) *defaultOperationLogModel {
	m.query = query
	m.queryArgs = args
	return m
}

func (m *defaultOperationLogModel) Limit(limit int) *defaultOperationLogModel {
	m.limit = limit
	return m
}

func (m *defaultOperationLogModel) Offset(offset int) *defaultOperationLogModel {
	m.offset = offset
	return m
}

func (m *defaultOperationLogModel) OrderBy(orderBy string) *defaultOperationLogModel {
	m.orderBy = orderBy
	return m
}
func (m *defaultOperationLogModel) Delete(ctx context.Context, id int64) error {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, operationLogIdKey)
	return err
}

func (m *defaultOperationLogModel) FindOne(ctx context.Context, id int64) (*OperationLog, error) {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, id)
	var resp OperationLog
	err := m.QueryRowCtx(ctx, &resp, operationLogIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND deleted_at = 0 limit 1", operationLogRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultOperationLogModel) Insert(ctx context.Context, data *OperationLog) (sql.Result, error) {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, operationLogRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.OperationAt, data.UserId, data.Username, data.Operation, data.Method, data.RequestParams, data.ResponseParams, data.Time, data.Ip)
	}, operationLogIdKey)
	return ret, err
}

func (m *defaultOperationLogModel) Update(ctx context.Context, data *OperationLog) error {
	operationLogIdKey := fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, operationLogRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.OperationAt, data.UserId, data.Username, data.Operation, data.Method, data.RequestParams, data.ResponseParams, data.Time, data.Ip, data.Id)
	}, operationLogIdKey)
	return err
}

// 根据条件进行查询一条数据
func (m *defaultOperationLogModel) First(ctx context.Context) (*OperationLog, error) {
	query := m.query

	queryArgs := m.queryArgs
	orderBy := m.orderBy
	var resp OperationLog
	sql := fmt.Sprintf("select %s from %s", operationLogRows, m.table)

	if query != "" {
		sql += " where " + query
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
	}

	sql += " AND deleted_at = 0 limit 1"

	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 根据条件进行列表查询
func (m *defaultOperationLogModel) Find(ctx context.Context) ([]*OperationLog, error) {

	query := m.query
	queryArgs := m.queryArgs
	orderBy := m.orderBy

	var resp []*OperationLog
	sql := fmt.Sprintf("select %s from %s", operationLogRows, m.table)

	if query != "" {
		sql += " where " + query + " AND deleted_at = 0"
	} else {
		sql += " where deleted_at = 0"
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
	}

	limit := m.limit
	offset := m.offset

	// 查询条件
	if limit > 0 {
		sql += fmt.Sprintf(" LIMIT %d", limit)
	}

	if offset > 0 {
		sql += fmt.Sprintf(" OFFSET %d", offset)
	}

	err := m.QueryRowsNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 统计字段
func (m *defaultOperationLogModel) Count(ctx context.Context) (int64, error) {
	query := m.query
	queryArgs := m.queryArgs
	sql := fmt.Sprintf("select count(`id`) from %s", m.table)
	if query != "" {
		sql += " where " + query
	}
	var resp int64
	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}
func (m *defaultOperationLogModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheOperationLogIdPrefix, primary)
}

func (m *defaultOperationLogModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND deleted_at = 0 limit 1", operationLogRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultOperationLogModel) tableName() string {
	return m.table
}
