// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package service

import (
	"context"

	"app/core/user/admin/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	LoginReq  = pb.LoginReq
	LoginResp = pb.LoginResp

	Service interface {
		// 管理员登录
		AdminLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error)
	}

	defaultService struct {
		cli zrpc.Client
	}
)

func NewService(cli zrpc.Client) Service {
	return &defaultService{
		cli: cli,
	}
}

// 管理员登录
func (m *defaultService) AdminLogin(ctx context.Context, in *LoginReq, opts ...grpc.CallOption) (*LoginResp, error) {
	client := pb.NewServiceClient(m.cli.Conn())
	return client.AdminLogin(ctx, in, opts...)
}
