// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	oauth "app/core/user/admin/api/internal/handler/oauth"
	"app/core/user/admin/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/user_info",
				Handler: oauth.UserInfoHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/user/admin"),
	)
}
