// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	login "app/core/user/authn/api/internal/handler/login"
	oauth "app/core/user/authn/api/internal/handler/oauth"
	"app/core/user/authn/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/admin/login",
				Handler: login.AdminLoginHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/authn"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/refresh",
				Handler: oauth.RefreshHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/token",
				Handler: oauth.TokenHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/validation",
				Handler: oauth.ValidationHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/authn"),
	)
}
