// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"app/core/user/admin/rpc/internal/logic"
	"app/core/user/admin/rpc/internal/svc"
	"app/core/user/admin/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// 管理员登录
func (s *ServiceServer) AdminLogin(ctx context.Context, in *pb.LoginReq) (*pb.LoginResp, error) {
	l := logic.NewAdminLoginLogic(ctx, s.svcCtx)
	return l.AdminLogin(in)
}
