// Code generated by goctl. DO NOT EDIT.
// Source: admin.proto

package server

import (
	"context"

	"app/core/user/admin/rpc/internal/logic"
	"app/core/user/admin/rpc/internal/svc"
	"app/core/user/admin/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取单个管理员
func (s *ServiceServer) AdminShow(ctx context.Context, in *pb.AdminShowReq) (*pb.LoginResp, error) {
	l := logic.NewAdminShowLogic(ctx, s.svcCtx)
	return l.AdminShow(in)
}
