version: "3"

#
# global vars: https://taskfile.dev/#/usage?id=variables
#
#vars:
#  VAR1: "some-var"

# global env:
env:
  DB_URL: "mysql://root:123456@127.0.0.1:3306"

# env file:
#dotenv:
#  - .env

################################################################################################

tasks:

  run:
    cmds:
      - go run main.go

  # ref: https://go-zero.dev/cn/docs/goctl/installation/
  install:
    cmds:
      - GOPROXY=https://goproxy.cn/,direct go install github.com/zeromicro/go-zero/tools/goctl@latest
      - goctl -v
      - goctl env check -i -f --verbose

  init:db:
    cmds:
      #      - usql --help
      - usql ${DB_URL} -f "model/sql/db.sql"
      - usql ${DB_URL} -f "model/sql/schema.sql"


  # 运行：
  run:api:
    cmds:
      - |
        cd api/; go run main.go -f etc/main.yaml

  # 运行：
  run:rpc:
    cmds:
      - |
        cd rpc/; go run main.go -f etc/main.yaml

  new:api:
    cmds:
      - goctl api new api

  new:rpc:
    cmds:
      - goctl rpc new rpc

  # 更改proto文件， 可以方便生成业务框架代码
  gen:rpc:
    cmds:
      # - cd hello_rpc/; goctl rpc protoc rpc.proto --go_out=./pb --go-grpc_out=./pb --zrpc_out=.
      #      - cd rpc/; goctl rpc protoc main.proto --go_out=. --go-grpc_out=. --zrpc_out=. --style gozero
      - goctl rpc protoc "./rpc/pb/admin.proto" --go_out=./rpc --go-grpc_out=./rpc --zrpc_out=./rpc --style gozero --home ../../../../template
    ignore_error: true

  # ref: https://go-zero.dev/cn/docs/design/grammar
  # todo x: fix 报错, 注意 go.work 添加子路径
  gen:api:
    cmds:
      #      - cd api; goctl api go --api api.api --dir . --style gozero
      - goctl api go --api "./api/admin.api" --dir="./api" --style gozero --home ../../../../template

  # 基于 sql， 生成 model CRUD 代码
  gen:model:
    cmds:
      #      - goctl model mysql ddl -src="./*.sql" -dir="./sql/model" -c --style gozero
      - goctl model mysql ddl -src="./rpc/data/sql/*.sql" -dir="./model" -c --style gozero --home ../../../../template

  # 生成 docker 构建文件
  gen:docker:
    cmds:
      - cd api; goctl docker -go main.go
      - cd rpc; goctl docker -go main.go
    ignore_error: true

  # 构建 docker 镜像：
  build:docker:api:
    cmds:
      - docker build -t api:v1 -f api/Dockerfile .

  tidy:
    cmds:
      #      - go get -u github.com/zeromicro/zero-contrib/zrpc/registry/consul
      - go mod tidy -v

  fmt:
    cmds:
      - go fmt .

  # 测试 API 服务运行正常：
  api:test:
    cmds:
      - curl -i -X GET http://localhost:8888/from/you
      - curl -i -X GET http://localhost:8888/license/key
      - open http://localhost:8888/from/you
      - open http://localhost:8888/license/key
