// Code generated by goctl. DO NOT EDIT.
// Source: menu.proto

package server

import (
	"context"

	"app/core/system/menu/rpc/internal/logic"
	"app/core/system/menu/rpc/internal/svc"
	"app/core/system/menu/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// 获取菜单
func (s *ServiceServer) TreeList(ctx context.Context, in *pb.TreeListReq) (*pb.TreeListResp, error) {
	l := logic.NewTreeListLogic(ctx, s.svcCtx)
	return l.TreeList(in)
}

// 获取单个菜单
func (s *ServiceServer) Show(ctx context.Context, in *pb.ShowReq) (*pb.ShowResp, error) {
	l := logic.NewShowLogic(ctx, s.svcCtx)
	return l.Show(in)
}

// 保存菜单
func (s *ServiceServer) Save(ctx context.Context, in *pb.SaveReq) (*pb.SaveResp, error) {
	l := logic.NewSaveLogic(ctx, s.svcCtx)
	return l.Save(in)
}

// 删除菜单
func (s *ServiceServer) Delete(ctx context.Context, in *pb.SaveReq) (*pb.Response, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
