// Code generated by goctl. DO NOT EDIT.
// Source: menu.proto

package server

import (
	"context"

	"app/core/system/menu/rpc/internal/logic"
	"app/core/system/menu/rpc/internal/svc"
	"app/core/system/menu/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ServiceServer) Ping(ctx context.Context, in *pb.Request) (*pb.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
