// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { defineApp } from './core/defineApp'
export type { RuntimeConfig } from './core/defineApp'
// @umijs/renderer-*
export { createBrowserHistory, createHashHistory, createMemoryHistory, Helmet, HelmetProvider, createSearchParams, generatePath, matchPath, matchRoutes, Navigate, NavLink, Outlet, resolvePath, useLocation, useMatch, useNavigate, useOutlet, useOutletContext, useParams, useResolvedPath, useRoutes, useSearchParams, useAppData, useClientLoaderData, useRouteProps, useSelectedRoutes, useServerLoaderData, renderClient, __getRoot, Link, useRouteData, __useFetcher, withRouter } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/node_modules/.pnpm/@umijs+renderer-react@4.0.78_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react';
export type {  History } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/node_modules/.pnpm/@umijs+renderer-react@4.0.78_react-dom@18.1.0_react@18.1.0/node_modules/@umijs/renderer-react'
// umi/client/client/plugin
export { ApplyPluginsType, PluginManager } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/node_modules/.pnpm/umi@4.0.78_@babel+core@7.22.11_@types+react@18.2.21_eslint@8.35.0_postcss@8.4.28_prettier@3.0_adh5ikn5obcxota2toczmnn7fa/node_modules/umi/client/client/plugin.js';
export { history, createHistory } from './core/history';
export { terminal } from './core/terminal';
export { TestBrowser } from './testBrowser';
export const useServerInsertedHTML: Function = () => {};
// plugins
export { Access, useAccess, useAccessMarkedRoutes } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-access';
export { Provider, useModel } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-model';
export { useRequest, UseRequestProvider, request, getRequestInstance } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-request';
export { StyleSheetManager, ThemeProvider, createGlobalStyle, css, keyframes, styled, useTheme } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-styledComponents';
// plugins types.d.ts
export * from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-access/types.d';
export * from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-antd/types.d';
export * from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-layout/types.d';
export * from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/src/.umi/plugin-request/types.d';
