// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	adminmenu "app/biz/admin/internal/handler/admin/menu"
	"app/biz/admin/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/trees",
				Handler: adminmenu.GetTreesHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/:id",
				Handler: adminmenu.ShowHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/",
				Handler: adminmenu.AddHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/:id",
				Handler: adminmenu.EditHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1/admin/menu"),
	)
}
