// Code generated by goctl. DO NOT EDIT.
// Source: menu.proto

package service

import (
	"context"

	"app/core/system/menu/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = pb.Request
	Response = pb.Response

	Service interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultService struct {
		cli zrpc.Client
	}
)

func NewService(cli zrpc.Client) Service {
	return &defaultService{
		cli: cli,
	}
}

func (m *defaultService) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := pb.NewServiceClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
