// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import styled, { ThemeProvider, createGlobalStyle, css, keyframes, StyleSheetManager, useTheme } from '/Users/return/workspace/mygo/zerocmf-micro/client/antd-admin/node_modules/.pnpm/styled-components@6.0.0-rc.0_react-dom@18.2.0_react@18.2.0/node_modules/styled-components';
export { styled, ThemeProvider, createGlobalStyle, css, keyframes, StyleSheetManager, useTheme };
