// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import { styledComponents as styledComponentsConfig } from '@/app';
export function rootContainer(container) {
  const globalStyle = styledComponentsConfig.GlobalStyle ? <styledComponentsConfig.GlobalStyle /> : null;
  return (
    <>
      {globalStyle}
      {container}
    </>
  );
}
