// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	adminUserFieldNames          = builder.RawFieldNames(&AdminUser{})
	adminUserRows                = strings.Join(adminUserFieldNames, ",")
	adminUserRowsExpectAutoSet   = strings.Join(stringx.Remove(adminUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	adminUserRowsWithPlaceHolder = strings.Join(stringx.Remove(adminUserFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheAdminUserIdPrefix = "cache:adminUser:id:"
)

type (
	adminUserModel interface {
		Where(query string, args ...interface{}) *defaultAdminUserModel
		Limit(limit int) *defaultAdminUserModel
		Offset(offset int) *defaultAdminUserModel
		OrderBy(query string) *defaultAdminUserModel
		First(ctx context.Context) (*AdminUser, error)
		Find(ctx context.Context) ([]*AdminUser, error)
		Count(ctx context.Context) (int64, error)
		Insert(ctx context.Context, data *AdminUser) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*AdminUser, error)
		Update(ctx context.Context, data *AdminUser) error
		Delete(ctx context.Context, id int64) error
	}

	defaultAdminUserModel struct {
		sqlc.CachedConn
		table     string
		query     string
		queryArgs []interface{}
		limit     int
		offset    int
		orderBy   string
	}

	AdminUser struct {
		Id            int64     `db:"id"`
		CreatedAt     time.Time `db:"created_at"`
		UpdatedAt     time.Time `db:"updated_at"`
		DeletedAt     time.Time `db:"deleted_at"`
		Status        int64     `db:"status"`         // 状态： <0=异常状态, >0=正常状态, 1=已分配, -1=封禁
		Desc          string    `db:"desc"`           // 描述信息
		Salt          string    `db:"salt"`           // 加密盐
		Password      string    `db:"password"`       // 密码
		Username      string    `db:"username"`       // 用户名
		UsernameSn    string    `db:"username_sn"`    // 用户名编号
		Email         string    `db:"email"`          // 邮箱
		MobileNo      string    `db:"mobile_no"`      // 手机号
		MobileCountry string    `db:"mobile_country"` // 手机号国家码
		NickName      string    `db:"nick_name"`      // 昵称
	}
)

func newAdminUserModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultAdminUserModel {
	return &defaultAdminUserModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`admin_user`",
	}
}

func (m *defaultAdminUserModel) withSession(session sqlx.Session) *defaultAdminUserModel {
	return &defaultAdminUserModel{
		CachedConn: m.CachedConn.WithSession(session),
		table:      "`admin_user`",
	}
}

func (m *defaultAdminUserModel) Where(query string, args ...interface{}) *defaultAdminUserModel {
	m.query = query
	m.queryArgs = args
	return m
}

func (m *defaultAdminUserModel) Limit(limit int) *defaultAdminUserModel {
	m.limit = limit
	return m
}

func (m *defaultAdminUserModel) Offset(offset int) *defaultAdminUserModel {
	m.offset = offset
	return m
}

func (m *defaultAdminUserModel) OrderBy(orderBy string) *defaultAdminUserModel {
	m.orderBy = orderBy
	return m
}
func (m *defaultAdminUserModel) Delete(ctx context.Context, id int64) error {
	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, adminUserIdKey)
	return err
}

func (m *defaultAdminUserModel) FindOne(ctx context.Context, id int64) (*AdminUser, error) {
	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, id)
	var resp AdminUser
	err := m.QueryRowCtx(ctx, &resp, adminUserIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? AND deleted_at = 0 limit 1", adminUserRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultAdminUserModel) Insert(ctx context.Context, data *AdminUser) (sql.Result, error) {
	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, adminUserRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.Status, data.Desc, data.Salt, data.Password, data.Username, data.UsernameSn, data.Email, data.MobileNo, data.MobileCountry, data.NickName)
	}, adminUserIdKey)
	return ret, err
}

func (m *defaultAdminUserModel) Update(ctx context.Context, data *AdminUser) error {
	adminUserIdKey := fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (json sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, adminUserRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.DeletedAt, data.Status, data.Desc, data.Salt, data.Password, data.Username, data.UsernameSn, data.Email, data.MobileNo, data.MobileCountry, data.NickName, data.Id)
	}, adminUserIdKey)
	return err
}

// 根据条件进行查询一条数据
func (m *defaultAdminUserModel) First(ctx context.Context) (*AdminUser, error) {
	query := m.query

	queryArgs := m.queryArgs
	orderBy := m.orderBy
	var resp AdminUser
	sql := fmt.Sprintf("select %s from %s", adminUserRows, m.table)

	if query != "" {
		sql += " where " + query
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
	}

	sql += " AND deleted_at = 0 limit 1"

	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 根据条件进行列表查询
func (m *defaultAdminUserModel) Find(ctx context.Context) ([]*AdminUser, error) {

	query := m.query
	queryArgs := m.queryArgs
	orderBy := m.orderBy

	var resp []*AdminUser
	sql := fmt.Sprintf("select %s from %s", adminUserRows, m.table)

	if query != "" {
		sql += " where " + query + " AND deleted_at = 0"
	} else {
		sql += " where deleted_at = 0"
	}

	// 排序
	if orderBy != "" {
		sql += fmt.Sprintf(" ORDER BY %s", orderBy)
	}

	limit := m.limit
	offset := m.offset

	// 查询条件
	if limit > 0 {
		sql += fmt.Sprintf(" LIMIT %d", limit)
	}

	if offset > 0 {
		sql += fmt.Sprintf(" OFFSET %d", offset)
	}

	err := m.QueryRowsNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

// 统计字段
func (m *defaultAdminUserModel) Count(ctx context.Context) (int64, error) {
	query := m.query
	queryArgs := m.queryArgs
	sql := fmt.Sprintf("select count(`id`) from %s", m.table)
	if query != "" {
		sql += " where " + query
	}
	var resp int64
	err := m.QueryRowNoCacheCtx(ctx, &resp, sql, queryArgs...)
	switch err {
	case nil:
		return resp, nil
	default:
		return 0, err
	}
}
func (m *defaultAdminUserModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheAdminUserIdPrefix, primary)
}

func (m *defaultAdminUserModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? AND deleted_at = 0 limit 1", adminUserRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultAdminUserModel) tableName() string {
	return m.table
}
