// Code generated by goctl. DO NOT EDIT.
// Source: log.proto

package server

import (
	"context"

	"app/core/log/rpc/internal/logic"
	"app/core/log/rpc/internal/svc"
	"app/core/log/rpc/pb"
)

type ServiceServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedServiceServer
}

func NewServiceServer(svcCtx *svc.ServiceContext) *ServiceServer {
	return &ServiceServer{
		svcCtx: svcCtx,
	}
}

// 系统日志记录
func (s *ServiceServer) LogSystem(ctx context.Context, in *pb.SystemLogReq) (*pb.SystemLogResp, error) {
	l := logic.NewLogSystemLogic(ctx, s.svcCtx)
	return l.LogSystem(in)
}
